### ISSUE TITLE
Interface issue in template editor - cursor is misplaced

### ISSUE THREAD

**Issue by inspiredearth** [invoiceninja/flutter-client#170]
Version 5.0.34-28

I am editing an invoice.

I notice that the editor (Footer, in this instance) has an issue with where the cursor shows up. In this screenshot you'll see the cursor is sitting at the "e" in "here". Yet the actual cursor point (where text is currently typing into the GUI) is at the end of the text, "... but cursor is to the left|". So the cursor is mis-positioned. This makes it kinda tricky to work with.

![image](https://user-images.githubusercontent.com/667395/101839220-dccd8b00-3ba6-11eb-96e3-f281b66698e5.png)

It seems fine on the first line in the editor, but occurs once I get to a second line. I also see that there's blank space to the right of the first line, about the same width as the mis-alignment of the cursor. I am thinking that might have something to do with it.

**Comment by hillelcoren** [comment]
I believe this issue is caused by a problem with the framework we're using, it should hopefully be fixed in the future.

https://github.com/flutter/flutter/issues/41630

Until then if you're able to use the macOS desktop app it should perform better.

**Comment by jonathannz** [comment]
There's a MacOS desktop app?

A search on Google and App Store didn't turn up any useful links. Where do I obtain it from?

**Comment by hillelcoren** [comment]
If you click the info icon in the bottom left corner you'll see an 'App platforms' option with links to all of the apps.

**Comment by jonathannz** [comment]
~~Is this the Chrome application you're referring to? (Which I discovered earlier today, when I saw an unfamiliar icon in my address bar whilst using Ninja).~~

~~Or is it a native MacOS app? If it's this, then clicking the MacOS button in the 'App platforms' isn't taking me to it.~~

Actually, the issue was that when logged into Ninja, clicking that button briefly takes me to http://download.invoiceninja.com/macos, and then that quickly redirects to my Ninja URL, meaning I couldn't get the download. I had to open a new private browser window, and paste in that URL. Now I've got a download.

**Comment by hillelcoren** [comment]
Good to know, thanks! We'll look into it...

**Comment by hillelcoren** [comment]
This should be resolved in the latest version

**Comment by lonix1** [comment]
I'm using 5.1.34 and the issue still exists here:
- linux: firefox, chromium
- windows: edge, firefox

The problems are with most multiline scrollable textboxes, but most importantly with the invoice editor's "includes css" tab. The positioning bug makes it wholly unusable, so I need to copy-and-paste to a notepad, edit there, then copy-and-paste back into the app.

Problems:
- click on text doesn't place cursor in correct location
- selecting text (with mouse) selects wrong text
- result: when edit made the change is applied to some other text

This is an old upstream bug, and they don't seem pressed to fix it: [[1]](https://github.com/flutter/flutter/issues/79120), [[2]](https://github.com/flutter/flutter/issues/41630)

Is there any workaround other than what I've mentioned above? Maybe the flutter platform for e.g. has different kinds of textboxes, or something like that?

On the tests I've done multiline scrollable textboxes are totally unusable, so although this is an upstream problem, it's quite bad and worth keeping an eye on.

**Comment by hillelcoren** [comment]
Have you had a chance to try the CanvasKit renderer? You can enable it by adding `FLUTTER_RENDERER=selfhosted-canvaskit` to the .env file and running php artisan optimize. The WASM version takes a bit longer to download but in theory should be more performant.

**Comment by lonix1** [comment]
- I added that to my docker `.env`
- I restarted the app
- Surprise: it took me to the `/setup` page! I thought my instance was broken (not a problem though as I made a backup). I setup again, logged in. Strangely after that everything was as before! All the data was intact.
- I went to the "includes" tab. Same as before unfortunately. :(

What I don't get is why the flutter folks haven't address this in so long. It seems like a major deal breaker for any app that needs rich text editing. We all need to +1 [this issue](https://github.com/flutter/flutter/issues/41630) to get their attention.

(On a side note I'm super interested there's now a wasm client)

**Comment by hmnd** [comment]
@hillelcoren I wonder if changing the editor to use [singerdmx/flutter-quill](https://github.com/singerdmx/flutter-quill) would perhaps solve this issue? [This commit](https://github.com/singerdmx/flutter-quill/commit/54c3eb446e2b90ec0a977d29eb0f21e2752dd07f) appears to have fixed issues with web support in that project.
As @lonix1 mentioned, it doesn't look like the flutter team is going to address the issue with their component any time soon :(

**Comment by hillelcoren** [comment]
The package doesn't support HTML and the issue linked is unrelated to the specific problem here.
